### ISSUE TITLE
Reference to the window jQuery object is not set after script

### ISSUE THREAD

**Issue by binary-zero-one** [sitespeedio/coach-core#61]
This issue is related to #21 
It is specified that window.$ doesn't refer to the object after script, but also missed that window.jQuery itself is undefined too.
![Image](https://user-images.githubusercontent.com/75141398/124439872-776f0080-dd69-11eb-88dd-e583ea7ddc7b.png)
Fix is to include one statement on line 22 after [this line](https://github.com/sitespeedio/coach-core/blob/main/lib/dom/performance/jquery.js#L21):
`window.jQuery = keepRef;`

**Comment by soulgalore** [comment]
Thank you @binary-zero-one let me push a new release tomorrow.

**Comment by soulgalore** [comment]
Released the updated version in sitespeed.io 17.8.3
